package lib

const CODE_ACCESS_DENIED = 403
const NOT_FOUND = 404
const GOOD_REQUEST_BAD_CONTENT = 422
const BAD_REQUEST = 400
const SERVICE_UNAVAILABLE = 503
const INTERNAL_ERROR = 500
const GATEWAY_ERROR = 502
